plugins {
    id 'fabric-loom' version '1.7.4'
    id 'maven-publish'
}

group = 'com.hellcitmod'
version = '0.2.2'

repositories {
    mavenCentral()
    maven { url = 'https://maven.fabricmc.net/' }
    maven { url = 'https://maven.terraformersmc.com/' }
}

dependencies {
    minecraft 'com.mojang:minecraft:1.21.4'
    mappings 'net.fabricmc:yarn:1.21.4+build.1:v2'
    modImplementation 'net.fabricmc:fabric-loader:0.16.14'
    modImplementation 'net.fabricmc.fabric-api:fabric-api:0.117.5+1.21.4'
    modCompileOnly 'com.terraformersmc:modmenu:11.0.3'
}

java {
    withSourcesJar()
    sourceCompatibility = JavaVersion.VERSION_21
    targetCompatibility = JavaVersion.VERSION_21
}

tasks.withType(JavaCompile).configureEach {
    options.release = 21
}
